### ISSUE TITLE
Allow to specify if attribute is serialized

### ISSUE THREAD

**Issue by StephanHoyer** [StephanHoyer/modelz#2]
User should be able to determine, if attribute should be serialized or not

```
fieldname: {
  type: 'string',
  required: true,
  serialize: false   
}
```

The value can be:
- `true` - value will be serialized
- `false` - value will not be serialized
- `function(value, object) {}` - value will be serialized by caling the function, first param is the current value of the field, second is the object itself

Computed properties should be omitted by default, all others should be included. This should be configurable with global config.

**Comment by der-On** [comment]
Instead define get/set functions. This way we can even have computed properties.

**Comment by StephanHoyer** [comment]
`enumerable`
